# Mapeo de campos entre BaseDatos.xlsx y SolicitudOrden.xlsx
CAMPOS = {
    'dia': '{dia}',
    'mes': '{mes}',
    'radi': '{radi}',
    'quipu_proyecto': '{quipu_proyecto}',
    'nombre_proyecto': '{nombre_proyecto}',
    'nombre_director_proyecto': '{nombre_director_proyecto}',
    'numero_identidad_director_proyecto': '{numero_identidad_director_proyecto}',
    'correo_director_proyecto': '{correo_director_proyecto}',
    'numero_resolucion': '{numero_resolucion}',
    'fecha_resolucion': '{fecha_resolucion}',
    'complemento_resolucion': '{complemento_resolucion}',
    'complemento_resolucion': '{complemento_resolucion}',
    'nivel_academico_justificacion': '{nivel_academico_justificacion}',
    'perfil_profesional_justificacion': '{perfil_profesional_justificacion}',
    'actividades_justificacion': '{actividades_justificacion}',
    'complemento_justificacion': '{complemento_justificacion}',
    'numero_causal': '{numero_causal}',
    'valor_hora': '{valor_hora}',
    'perfil_tarifa': '{perfil_tarifa}',
    'tipo_rubro': '{tipo_rubro}',
    'cantidad_pagos': '{cantidad_pagos}',
    'valor_contrato': '{valor_contrato}',
    'nombre_arl': '{nombre_arl}',
    'causal': '{causal}',
    'nivel_academico_objeto': '{nivel_academico_objeto}',
    'idioma_programa_objeto': '{idioma_programa_objeto}',
    'nombre_proyecto': '{nombre_proyecto}',
    'fecha_inicio': '{fecha_inicio}',
    'fecha_terminacion': '{fecha_terminacion}',
    'lugar_ejecucion': '{lugar_ejecucion}',
    'nombre_contratista': '{nombre_contratista}',
    'documento_contratista': '{documento_contratista}',
    'correo_inst_contratista': '{correo_inst_contratista}',
    'equis': '{equis}',
    'obligacion_1': '{obligacion_1}',
    'obligacion_2': '{obligacion_2}',
    'obligacion_3': '{obligacion_3}',
    'obligacion_4': '{obligacion_4}',
    'obligacion_5': '{obligacion_5}',
    'obligacion_6': '{obligacion_6}',
    'obligacion_7': '{obligacion_7}',
    'obligacion_8': '{obligacion_8}',
    'obligacion_9': '{obligacion_9}',
    'obligacion_10': '{obligacion_10}',
    'obligacion_11': '{obligacion_11}',
    'obligacion_12': '{obligacion_12}',
    'obligacion_13': '{obligacion_13}',
    'obligacion_14': '{obligacion_14}',
    'obligacion_15': '{obligacion_15}',
    'obligacion_16': '{obligacion_16}',
    'obligacion_17': '{obligacion_17}',
    'obligacion_18': '{obligacion_18}',
    'obligacion_19': '{obligacion_19}',
    'obligacion_20': '{obligacion_20}',
    'obligacion_21': '{obligacion_21}',
    'obligacion_22': '{obligacion_22}',
    'obligacion_23': '{obligacion_23}',
    'obligacion_24': '{obligacion_24}',
    'obligacion_25': '{obligacion_25}'
}

# Configuración de hojas
HOJA_SOLICITUD = 'FT Solicitud_Orden'


# Lista de campos de obligaciones
OBLIGACIONES = [
    'obligacion_1',
    'obligacion_2',
    'obligacion_3',
    'obligacion_4',
    'obligacion_5',
    'obligacion_6',
    'obligacion_7',
    'obligacion_8',
    'obligacion_9',
    'obligacion_10',
    'obligacion_11',
    'obligacion_12',
    'obligacion_13',
    'obligacion_14',
    'obligacion_15',
    'obligacion_16',
    'obligacion_17',
    'obligacion_18',
    'obligacion_19',
    'obligacion_20',
    'obligacion_21',
    'obligacion_22',
    'obligacion_23',
    'obligacion_24',
    'obligacion_25'
    # puedes añadir más aquí si tu base de datos crece
]