# Mapeo de campos entre BaseDatos.xlsx y SolicitudOrden.xlsx
CAMPOS = {
    'dia': '{dia}',
    'mes': '{mes}',
    'radi': '{radi}',
    'quipu_proyecto': '{quipu_proyecto}',
    'nombre_proyecto': '{nombre_proyecto}',
    'nombre_director_proyecto': '{nombre_director_proyecto}',
    'numero_identidad_director_proyecto': '{numero_identidad_director_proyecto}', 
    'correo_director_proyecto': '{correo_director_proyecto}',   
    'numero_resolucion': '{numero_resolucion}',
    'fecha_resolucion': '{fecha_resolucion}',
    'complemento_resolucion': '{complemento_resolucion}',
    'justificacion': '{justificacion}',
    'rubros_valores_justificacion': '{rubros_valores_justificacion}',
    'objeto': '{objeto}',
    'bien_uno':'{bien_uno}',
    'bien_dos': '{bien_dos}',
    'bien_tres': '{bien_tres}',
    'bien_cuatro': '{bien_cuatro}',
    'bien_cinco': '{bien_cinco}',
    'equis_bienes': '{equis_bienes}',
    'cantidad_bien_uno': '{cantidad_bien_uno}',
    'cantidad_bien_dos': '{cantidad_bien_dos}',
    'cantidad_bien_tres': '{cantidad_bien_tres}',
    'cantidad_bien_cuatro': '{cantidad_bien_cuatro}',
    'cantidad_bien_cinco': '{cantidad_bien_cinco}',
    'equis_obligaciones': '{equis_obligaciones}',
    'obligacion_uno': '{obligacion_uno}',
    'obligacion_dos': '{obligacion_dos}',
    'obligacion_tres': '{obligacion_tres}',
    'obligacion_cuatro': '{obligacion_cuatro}',
    'obligacion_cinco': '{obligacion_cinco}',
    'plazo_entrega': '{plazo_entrega}',
    'fecha_inicio': '{fecha_inicio}',
    'cantidad_pagos': '{cantidad_pagos}',
    'valor_pago': '{valor_pago}',
    'valor_contrato': '{valor_contrato}',
    'lugar_ejecucion': '{lugar_ejecucion}',
    'nombre_contratista': '{nombre_contratista}',
    'documento_contratista': '{documento_contratista}',
    'direccion_contratista': '{direccion_contratista}',
    'ciudad_contratista': '{ciudad_contratista}',
    'correo_contratista': '{correo_contratista}',
    'telfijo_contratista': '{telfijo_contratista}',
    'cel_contratista': '{cel_contratista}'
}

# Configuración de hojas
HOJA_SOLICITUD = 'FT Solicitud_Orden'